---
language: ruby
rvm:
- 1.9.3
services:
- redis-server
cache: bundler
sudo: false
notifications:
  email: false
  campfire:
    rooms:
    - secure: ! 'MEV8s5rOzTuIUMKML5oC9fWNJnJY505hxFh2bdDXeZQTC9qah/FJvlImuRDq

        MSLUM5Mcf4PLOJfNIFPdTpZp6fkDUpwGpi6xu6mqwdGodtjRoehTRZZRYDIB

        W+Px3oWt0jMGLRVGA/jg9OxNztbyKRaZPzGSDglwIdbmapHL9sk='
