---
language: ruby
rvm:
- 1.9.3
- 2.1.0
- 2.2.0
services:
- redis-server
cache: bundler
sudo: false
addons:
  code_climate:
    repo_token: 372e51ba06971fc891747b4f1399cc9222678871c468c9205ebf1569077e53b2
notifications:
  email: false
  campfire:
    rooms:
    - secure: ! 'MEV8s5rOzTuIUMKML5oC9fWNJnJY505hxFh2bdDXeZQTC9qah/FJvlImuRDq

        MSLUM5Mcf4PLOJfNIFPdTpZp6fkDUpwGpi6xu6mqwdGodtjRoehTRZZRYDIB

        W+Px3oWt0jMGLRVGA/jg9OxNztbyKRaZPzGSDglwIdbmapHL9sk='
